/**
 * Settings schema — the single source of truth for the VSCode-style panel.
 *
 * Layout mirrors `SETTINGS_TREE`: category → group → fields. Every field maps to
 * one key path in settings.json; there are no aliases and no duplicate keys.
 */

import { PARAM_CATALOG } from '../../live2d/params.js'

/* helpers ---------------------------------------------------------------- */
const F = (key, label, extra = {}) => ({ key, label, ...extra })
const SW = (key, label) => F(key, label, { type: 'switch' })
const NUM = (key, label, extra = {}) => F(key, label, { type: 'number', ...extra })
const RNG = (key, label, min, max, step, unit, fmt) =>
  F(key, label, { type: 'range', min, max, step, unit, fmt })
const TXT = (key, label, extra = {}) => F(key, label, { type: 'text', ...extra })
const PWD = (key, label, extra = {}) => F(key, label, { type: 'password', ...extra })
const SEL = (key, label, options, extra = {}) => F(key, label, { type: 'select', options, ...extra })
const AREA = (key, label, rows) => F(key, label, { type: 'textarea', rows })
const LINES = (key, label, rows) => F(key, label, { type: 'lines', rows })
const BTNS = (id, items) => ({ type: 'buttons', id, items })
const RESULT = (id) => ({ type: 'result', id })
const INFO = (id, html) => ({ type: 'info', id, html })

const FPS_OPTIONS = [
  { value: 30, label: '30' },
  { value: 45, label: '45' },
  { value: 60, label: '60' },
  { value: 90, label: '90' },
  { value: 120, label: '120' },
]

const PROVIDER_OPTIONS = [
  { value: 'auto', label: 'Auto (GPT-SoVITS first, online as fallback)' },
  { value: 'gptsovits', label: 'GPT-SoVITS (local voice cloning)' },
  { value: 'openai', label: 'Online TTS API (OpenAI-compatible)' },
  { value: 'off', label: 'Off' },
]

const LANG_OPTIONS = [
  { value: 'auto', label: 'Auto-detect' },
  { value: 'zh-CN', label: 'Chinese (Mandarin)' },
  { value: 'ja-JP', label: '日本語' },
  { value: 'en-US', label: 'English (US)' },
  { value: 'zh-TW', label: 'Chinese (Taiwan)' },
  { value: 'zh-HK', label: 'Cantonese' },
  { value: 'ko-KR', label: '한국어' },
  { value: 'fr-FR', label: 'Français' },
  { value: 'de-DE', label: 'Deutsch' },
  { value: 'es-ES', label: 'Español' },
  { value: 'ru-RU', label: 'Русский' },
]

const STT_LANG_OPTIONS = [
  { value: 'zh', label: 'Chinese' },
  { value: 'en', label: 'English' },
  { value: 'ja', label: '日本語' },
  { value: 'ko', label: '한국어' },
  { value: 'auto', label: 'Auto-detect' },
]

const CHAT_PRESETS = [
  { value: 'https://api.deepseek.com/v1', label: 'DeepSeek' },
  { value: 'https://api.openai.com/v1', label: 'OpenAI' },
  { value: 'https://api.moonshot.cn/v1', label: 'Moonshot AI' },
  { value: 'https://open.bigmodel.cn/api/paas/v4', label: 'Zhipu GLM' },
  { value: 'https://api.siliconflow.cn/v1', label: 'SiliconFlow' },
  { value: 'https://dashscope.aliyuncs.com/compatible-mode/v1', label: 'Alibaba Qwen' },
  { value: 'https://ark.cn-beijing.volces.com/api/v3', label: 'Volcengine Ark' },
  { value: 'http://localhost:11434/v1', label: 'Ollama (local)' },
  { value: 'http://localhost:1234/v1', label: 'LM Studio (local)' },
  { value: '__custom__', label: 'Custom…' },
]

/**
 * The tree. `id` values are stable — they are used for navigation state and for
 * the `#settings-nav` links.
 */
/**
 * Model parameters — one control per parameter psd2live generates, grouped the
 * way its cdi3.json declares them. Each can be left automatic, nudged by an
 * offset, or pinned to a fixed value.
 */
const PARAM_SECTION = {
  id: 'params',
  label: 'Model parameters',
  groups: [
    {
      id: 'overview',
      label: 'Overview',
      fields: [
        SW('modelParams.enabled', 'Enable manual overrides'),
        INFO(
          'params-info',
          'This model was generated by psd2live: 18 parameters in 6 groups, matching its specification. In auto mode you can set a lower and an upper limit to clamp the automatic result, and the curve on the right shows the live value. Switch a parameter to Offset or Fixed to override it directly.'
        ),
        RESULT('params-ranges'),
      ],
    },
    ...PARAM_CATALOG.map((g) => ({
      id: g.group,
      label: g.label,
      fields: g.params.map((p) => ({
        type: 'param',
        key: `modelParams.items.${p.id}`,
        id: p.id,
        label: `${p.name}`,
        owner: p.owner,
        group: g.label,
      })),
    })),
  ],
}

export const SETTINGS_TREE = [
  {
    id: 'display',
    label: 'Display',
    groups: [
      {
        id: 'window',
        label: 'Window',
        fields: [
          SW('display.alwaysOnTop', 'Always on top'),
          SEL('display.screenIndex', 'Monitor', [], { dynamic: 'screens' }),
          SEL('display.fps', 'Render frame rate', FPS_OPTIONS, { unit: 'FPS' }),
          SW('display.clickThrough', 'Smart mouse passthrough'),
          SW('display.keepInScreen', 'Keep on screen'),
          SW('display.startHidden', 'Start hidden'),
          SW('display.showTray', 'Show tray icon'),
        ],
      },
      {
        id: 'model',
        label: 'Model',
        fields: [
          TXT('model.path', 'Model path', { wide: true }),
          RNG('model.heightRatio', 'Character height', 0.2, 1.2, 0.01, '%', (v) => Math.round(v * 100)),
          RNG('model.scale', 'Size fine-tune', 0.4, 2, 0.01, '×', (v) => v.toFixed(2)),
          RNG('model.opacity', 'Opacity', 0.2, 1, 0.01, '%', (v) => Math.round(v * 100)),
          NUM('model.offsetX', 'Horizontal offset', { step: 1, unit: 'px' }),
          NUM('model.offsetY', 'Vertical offset', { step: 1, unit: 'px' }),
          SW('model.mirror', 'Flip horizontally'),
          SW('model.shadow', 'Drop shadow'),
          BTNS('model-actions', [{ id: 'reset-position', label: 'Reset position' }]),
        ],
      },
      {
        id: 'appearance',
        label: 'Appearance',
        fields: [
          F('ui.accent', 'Accent color', { type: 'color' }),
          RNG('ui.panelOpacity', 'Panel opacity', 0.4, 1, 0.01, '%', (v) => Math.round(v * 100)),
          RNG('ui.fontSize', 'UI font size', 11, 18, 0.5, 'px', (v) => v),
          RNG('ui.bubbleDuration', 'Bubble duration', 2, 60, 1, 's', (v) => v),
          SW('ui.dockVisible', 'Show quick-action bar'),
          SW('ui.showStatusHud', 'Show status overlay'),
        ],
      },
    ],
  },

  {
    id: 'gaze',
    label: 'Gaze',
    groups: [
      {
        id: 'follow',
        label: 'Tracking',
        fields: [
          SW('gaze.enabled', 'Enable gaze tracking'),
          RNG('gaze.intensity', 'Tracking strength', 0, 2, 0.01, '×', (v) => v.toFixed(2)),
          RNG('gaze.eyeAmount', 'Eye movement amount', 0, 1.5, 0.01, '×', (v) => v.toFixed(2)),
          RNG('gaze.eyeMax', 'Eye movement limit', 0.1, 1, 0.01, '', (v) => v.toFixed(2)),
          RNG('gaze.headAmount', 'Head movement amount', 0, 1.5, 0.01, '×', (v) => v.toFixed(2)),
          RNG('gaze.headYawMax', 'Yaw limit', 0, 45, 0.5, '°', (v) => v),
          RNG('gaze.headPitchMax', 'Pitch limit', 0, 30, 0.5, '°', (v) => v),
          RNG('gaze.bodyAmount', 'Body movement amount', 0, 1, 0.01, '×', (v) => v.toFixed(2)),
          RNG('gaze.bodyMax', 'Body rotation limit', 0, 10, 0.5, '°', (v) => v),
          RNG('gaze.smoothing', 'Follow speed', 0.01, 1, 0.01, '', (v) => v.toFixed(2)),
        ],
      },
      {
        id: 'natural',
        label: 'Naturalness',
        fields: [
          SW('gaze.distanceFalloff', 'Distance falloff'),
          NUM('gaze.maxDistance', 'Falloff distance', { step: 50, min: 200, max: 4000, unit: 'px' }),
          SW('gaze.idleDrift', 'Idle drift'),
          RNG('gaze.driftAmount', 'Drift amount', 0, 1, 0.01, '', (v) => v.toFixed(2)),
          RNG('gaze.driftSpeed', 'Drift speed', 0.05, 2, 0.05, '×', (v) => v.toFixed(2)),
          SW('gaze.saccade', 'Micro-saccades'),
          RNG('gaze.saccadeMin', 'Min interval', 0.5, 10, 0.1, 's', (v) => v.toFixed(1)),
          RNG('gaze.saccadeMax', 'Max interval', 1, 20, 0.1, 's', (v) => v.toFixed(1)),
          SW('gaze.invertX', 'Invert horizontally'),
          SW('gaze.invertY', 'Invert vertically'),
          RESULT('rig-ranges'),
        ],
      },
    ],
  },

  {
    id: 'idle',
    label: 'Motion',
    groups: [
      {
        id: 'blink',
        label: 'Blink',
        fields: [
          SW('idle.autoBlink', 'Auto blink'),
          RNG('idle.blinkMin', 'Min interval', 0.6, 12, 0.1, 's', (v) => v.toFixed(1)),
          RNG('idle.blinkMax', 'Max interval', 1, 20, 0.1, 's', (v) => v.toFixed(1)),
          RNG('idle.blinkDuration', 'Blink duration', 0.05, 0.4, 0.005, 'ms', (v) => Math.round(v * 1000)),
          RNG('idle.doubleBlinkChance', 'Double-blink chance', 0, 1, 0.01, '%', (v) => Math.round(v * 100)),
        ],
      },
      {
        id: 'body',
        label: 'Breathing & physics',
        fields: [
          SW('idle.breath', 'Breathing'),
          RNG('idle.breathSpeed', 'Breathing speed', 0.2, 3, 0.05, '×', (v) => v.toFixed(2)),
          RNG('idle.breathAmount', 'Breathing depth', 0, 1, 0.05, '%', (v) => Math.round(v * 100)),
          SW('idle.physics', 'Physics'),
        ],
      },
      {
        id: 'motions',
        label: 'Motions',
        fields: [
          SW('idle.motionsEnabled', 'Play motions (master switch)'),
          SW('idle.autoMotion', 'Random motion when idle'),
          RNG('idle.motionMin', 'Min interval', 5, 120, 1, 's', (v) => v),
          RNG('idle.motionMax', 'Max interval', 6, 240, 1, 's', (v) => v),
          RNG('idle.motionSpeed', 'Playback speed', 0.2, 3, 0.05, '×', (v) => v.toFixed(2)),
          BTNS('motion-test', [
            { id: 'motion-nod', label: 'Nod' },
            { id: 'motion-shake', label: 'Shake head' },
          ]),
          RESULT('motion-result'),
        ],
      },
    ],
  },

  {
    id: 'petting',
    label: 'Petting',
    groups: [
      {
        id: 'interact',
        label: 'Interaction',
        fields: [
          SW('petting.enabled', 'Enable petting'),
          RNG('petting.minStrokeDistance', 'Trigger sensitivity', 1, 30, 1, 'px', (v) => v),
          SW('petting.hearts', 'Hearts'),
          RNG('petting.heartRate', 'Heart density', 0.2, 3, 0.1, '×', (v) => v.toFixed(1)),
          SW('petting.squint', 'Happy squint'),
          RNG('petting.headFollow', 'Head follows cursor', 0, 1, 0.05, '%', (v) => Math.round(v * 100)),
          SW('petting.sound', 'Petting sound'),
          SW('petting.reactions', 'Motion reactions'),
          SW('petting.speakLines', 'Speech reactions'),
        ],
      },
      {
        id: 'lines',
        label: 'Lines',
        fields: [
          LINES('petting.reactLines', 'While petting', 6),
          LINES('petting.greetLines', 'Petting starts', 3),
          LINES('petting.leaveLines', 'Petting stops', 3),
        ],
      },
    ],
  },

  {
    id: 'chat',
    label: 'Chat',
    groups: [
      {
        id: 'api',
        label: 'API',
        fields: [
          SEL('chat.baseUrl', 'API base URL', CHAT_PRESETS, { editable: true }),
          PWD('chat.apiKey', 'API Key'),
          TXT('chat.model', 'Model'),
          TXT('chat.extraHeaders', 'Extra headers', { wide: true }),
          BTNS('chat-test', [
            { id: 'test-llm', label: 'Test connection' },
            { id: 'list-models', label: 'List models' },
          ]),
          RESULT('llm-result'),
        ],
      },
      {
        id: 'generate',
        label: 'Generation',
        fields: [
          RNG('chat.temperature', 'Temperature', 0, 2, 0.05, '', (v) => v.toFixed(2)),
          RNG('chat.topP', 'Top P', 0.1, 1, 0.01, '', (v) => v.toFixed(2)),
          NUM('chat.maxTokens', 'Max response length', { step: 32, min: 32, max: 8192 }),
          SW('chat.stream', 'Streaming'),
          NUM('chat.timeoutMs', 'Timeout', { step: 5000, min: 5000, max: 600000, unit: 'ms' }),
          NUM('chat.maxHistory', 'Memory turns', { step: 2, min: 0, max: 100 }),
        ],
      },
      {
        id: 'persona',
        label: 'Persona',
        fields: [
          TXT('chat.personaName', 'Name'),
          AREA('chat.systemPrompt', 'System prompt', 12),
          SW('chat.autoGreeting', 'Greet on startup'),
          TXT('chat.greeting', 'Greeting text', { wide: true }),
          SW('chat.sendOnEnter', 'Send with Enter'),
          SW('chat.emotionTags', 'Parse emotion tags'),
          SW('chat.showThinking', 'Show thinking indicator'),
        ],
      },
    ],
  },

  {
    id: 'voice',
    label: 'Voice',
    groups: [
      {
        id: 'engine',
        label: 'Engine',
        fields: [
          { type: 'presets', id: 'voice-presets', label: 'Voice presets' },
          RESULT('preset-result'),
          SW('voice.ttsEnabled', 'Enable speech'),
          SEL('voice.ttsProvider', 'Speech engine', PROVIDER_OPTIONS),
          RNG('voice.volume', 'Volume', 0, 1, 0.01, '%', (v) => Math.round(v * 100)),
          SW('voice.autoSpeak', 'Speak replies automatically'),
          SW('voice.speakOnPet', 'Speak when petted'),
          BTNS('tts-test', [
            { id: 'test-tts', label: 'Preview' },
            { id: 'test-tts-ja', label: 'Japanese' },
            { id: 'test-tts-zh', label: 'Chinese' },
            { id: 'refresh-tts', label: 'Refresh status' },
            { id: 'reset-tts', label: 'Clear fallback history' },
          ]),
          RESULT('tts-status'),
          RESULT('tts-result'),
        ],
      },
      {
        id: 'language',
        label: 'Language',
        fields: [SEL('voice.languageMode', 'Speech language', LANG_OPTIONS), RESULT('lang-status')],
      },
      {
        id: 'pitch',
        label: 'Voice tone',
        fields: [
          RNG('voice.pitchShift', 'Pitch', 0.6, 1.6, 0.01, '%', (v) => `${v.toFixed(2)} (${v >= 1 ? '+' : ''}${Math.round((v - 1) * 100)})`),
          {
            type: 'chips',
            key: 'voice.pitchShift',
            label: 'Presets',
            options: [
              { value: 0.85, label: 'Deep' },
              { value: 0.95, label: 'Steady' },
              { value: 1.0, label: 'Natural' },
              { value: 1.1, label: 'Bright' },
              { value: 1.18, label: 'Young female' },
              { value: 1.38, label: 'Child' },
            ],
          },
        ],
      },
      {
        id: 'gptsovits',
        label: 'GPT-SoVITS',
        fields: [
          INFO(
            'gsv-info',
            'To use a persistent model, put your fine-tuned GPT and SoVITS weights into GPT_weights_v2ProPlus / SoVITS_weights_v2ProPlus and click Auto-detect to fill the paths in. With no fine-tuned weights, start with Reference audio mode for zero-shot cloning.'
          ),
          TXT('voice.gptsovits.root', 'Install folder', { wide: true }),
          SW('voice.gptsovits.autoStart', 'Start with the pet'),
          BTNS('gsv-actions', [
            { id: 'scan-gsv', label: 'Auto-detect' },
            { id: 'start-gsv', label: 'Start now' },
          ]),
          RESULT('gsv-result'),
          TXT('voice.gptsovits.baseUrl', 'Server URL', { wide: true }),
          SEL('voice.gptsovits.mode', 'Reference mode', [
            { value: 'weights', label: 'Persistent model (fine-tuned weights)' },
            { value: 'audio', label: 'Reference audio (zero-shot cloning)' },
          ]),
          TXT('voice.gptsovits.gptWeights', 'GPT weights path', { wide: true }),
          TXT('voice.gptsovits.sovitsWeights', 'SoVITS weights path', { wide: true }),
          TXT('voice.gptsovits.refAudio', 'Reference audio path', { wide: true }),
          TXT('voice.gptsovits.promptText', 'Reference audio text', { wide: true }),
          SEL('voice.gptsovits.promptLang', 'Reference language', [
            { value: 'zh', label: 'Chinese' },
            { value: 'ja', label: '日本語' },
            { value: 'en', label: 'English' },
            { value: 'ko', label: '한국어' },
            { value: 'yue', label: 'Cantonese' },
          ]),
          SEL('voice.gptsovits.textLang', 'Synthesis language', [
            { value: 'zh', label: 'Chinese' },
            { value: 'ja', label: '日本語' },
            { value: 'en', label: 'English' },
            { value: 'ko', label: '한국어' },
            { value: 'yue', label: 'Cantonese' },
            { value: 'auto', label: 'Auto-split Chinese and English' },
            { value: 'auto_yue', label: 'Auto-split Cantonese and English' },
            { value: 'all_ja', label: 'Japanese preferred' },
            { value: 'all_zh', label: 'Chinese preferred' },
          ]),
          SEL('voice.gptsovits.splitMethod', 'Text splitting', [
            { value: 'cut0', label: 'No splitting' },
            { value: 'cut1', label: 'Every 4 sentences' },
            { value: 'cut2', label: 'Every 50 characters' },
            { value: 'cut3', label: 'By Chinese period' },
            { value: 'cut4', label: 'By English period' },
            { value: 'cut5', label: 'By punctuation (recommended)' },
          ]),
        ],
      },
      {
        id: 'openai',
        label: 'Online TTS API',
        fields: [
          TXT('voice.openaiBaseUrl', 'API base URL', { wide: true }),
          PWD('voice.openaiApiKey', 'API Key'),
          TXT('voice.openaiModel', 'Model'),
          INFO('openai-info', 'Must be compatible with POST /audio/speech. If no key is set here, the Chat API key is reused.'),
          { key: 'voice.languageProfiles.zh-CN.openai', label: 'Chinese voice', type: 'select', options: [] },
          { key: 'voice.languageProfiles.ja-JP.openai', label: 'Japanese voice', type: 'select', options: [] },
          { key: 'voice.languageProfiles.en-US.openai', label: 'English voice', type: 'select', options: [] },
        ],
      },
      {
        id: 'lipsync',
        label: 'Lip sync',
        fields: [
          SW('voice.lipSync', 'Lip sync'),
          RNG('voice.lipSyncGain', 'Sensitivity', 0.1, 5, 0.1, '×', (v) => v.toFixed(1)),
          RNG('voice.lipSyncSmoothing', 'Smoothing', 0.02, 1, 0.01, '', (v) => v.toFixed(2)),
          RNG('voice.mouthMax', 'Max mouth open', 0.05, 1, 0.01, '%', (v) => Math.round(v * 100)),
        ],
      },
      {
        id: 'stt',
        label: 'Voice input',
        fields: [
          SW('voice.sttEnabled', 'Enable voice input'),
          TXT('voice.sttBaseUrl', 'Transcription API URL', { wide: true }),
          PWD('voice.sttApiKey', 'API Key'),
          TXT('voice.sttModel', 'Transcription model'),
          SEL('voice.sttLanguage', 'Transcription language', STT_LANG_OPTIONS),
          NUM('voice.sttMaxSeconds', 'Max recording length', { step: 5, min: 3, max: 300, unit: 's' }),
          SW('voice.sttAutoSend', 'Send after transcription'),
          TXT('voice.sttHotkey', 'Global hotkey'),
          BTNS('stt-actions', [{ id: 'apply-hotkey', label: 'Apply hotkey' }]),
          RESULT('stt-result'),
        ],
      },
    ],
  },

  PARAM_SECTION,

  {
    id: 'locks',
    label: 'Locks',
    groups: [
      {
        id: 'locked',
        label: 'Locked',
        fields: [RESULT('lock-list'), BTNS('lock-actions', [{ id: 'unlock-all', label: 'Unlock all' }])],
      },
    ],
  },

  {
    id: 'about',
    label: 'About',
    groups: [{ id: 'about', label: 'About', fields: [{ type: 'about' }] }],
  },
]

/** Flat list of every field that maps to a settings path. */
export const ALL_FIELDS = SETTINGS_TREE.flatMap((section) =>
  section.groups.flatMap((g) => g.fields.filter((f) => f.key))
)
